package com.example.mapper;

import com.example.CustomObject.PhoneAndBidAmount;
import com.example.pojo.BidInfo;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
import java.util.Map;

@Mapper
public interface BidInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_bid_info
     *
     * @mbg.generated Fri Jun 03 12:29:22 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_bid_info
     *
     * @mbg.generated Fri Jun 03 12:29:22 CST 2022
     */
    int insert(BidInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_bid_info
     *
     * @mbg.generated Fri Jun 03 12:29:22 CST 2022
     */
    int insertSelective(BidInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_bid_info
     *
     * @mbg.generated Fri Jun 03 12:29:22 CST 2022
     */
    BidInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_bid_info
     *
     * @mbg.generated Fri Jun 03 12:29:22 CST 2022
     */
    int updateByPrimaryKeySelective(BidInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_bid_info
     *
     * @mbg.generated Fri Jun 03 12:29:22 CST 2022
     */
    int updateByPrimaryKey(BidInfo record);

    Double selectTotalBidMoney();

    /**
     * Find top 10 recently bid information based on loan id
     */
    List<BidInfo> selectRecentlyBidInfoByLoanId(Map<String, Object> params);

    List<PhoneAndBidAmount> queryAllUsersAndBidAmounts();

    List<BidInfo> selectBidInfoByLoanId(Integer id);

    List<BidInfo> selectBidInfoByUserId(Integer id);
}