package com.example.mapper;

import com.example.pojo.IncomeRecord;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface IncomeRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_income_record
     *
     * @mbg.generated Fri Jun 03 12:29:22 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_income_record
     *
     * @mbg.generated Fri Jun 03 12:29:22 CST 2022
     */
    int insert(IncomeRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_income_record
     *
     * @mbg.generated Fri Jun 03 12:29:22 CST 2022
     */
    int insertSelective(IncomeRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_income_record
     *
     * @mbg.generated Fri Jun 03 12:29:22 CST 2022
     */
    IncomeRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_income_record
     *
     * @mbg.generated Fri Jun 03 12:29:22 CST 2022
     */
    int updateByPrimaryKeySelective(IncomeRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_income_record
     *
     * @mbg.generated Fri Jun 03 12:29:22 CST 2022
     */
    int updateByPrimaryKey(IncomeRecord record);

    List<IncomeRecord> selectIncomeRecordListByIncomeStatusAndDate(int incomeStatus);
}