package com.example.mapper;

import com.example.pojo.LoanInfo;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Select;

import java.util.List;
import java.util.Map;

@Mapper
public interface LoanInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_loan_info
     *
     * @mbg.generated Fri Jun 03 12:29:22 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_loan_info
     *
     * @mbg.generated Fri Jun 03 12:29:22 CST 2022
     */
    int insert(LoanInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_loan_info
     *
     * @mbg.generated Fri Jun 03 12:29:22 CST 2022
     */
    int insertSelective(LoanInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_loan_info
     *
     * @mbg.generated Fri Jun 03 12:29:22 CST 2022
     */
    LoanInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_loan_info
     *
     * @mbg.generated Fri Jun 03 12:29:22 CST 2022
     */
    int updateByPrimaryKeySelective(LoanInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_loan_info
     *
     * @mbg.generated Fri Jun 03 12:29:22 CST 2022
     */
    int updateByPrimaryKey(LoanInfo record);

    /**
     * get average rate for loan
     * @return
     */
    double selectHistoryAvgRate();

    /**
     * get loan information based on the product type
     * @param map
     * @return
     */
    List<LoanInfo> selectLoanInfoListByProductType(Map<String, Object> map);

    /**
     * Number of records in the database
     */
    int totalNumOfRows(Map<String, Object> map);

    /**
     * get loan information by loan id
     */
    LoanInfo selectLoanInfoById(int id);

    int updateLeftProductMoney(Map<String, Object> params);

    List<LoanInfo> selectLoanInfoListByProductStatus(int i);
}